spring:
  application:
    name: Projeto251
  datasource:
    url: jdbc:h2:mem:produto
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /banco